name: common_env
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - nvidia
  - rapidsai
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.12.2=haa95532_0
  - freetype=2.14.1=h57928b3_0
  - glib=2.84.4=h60240c0_0
  - glib-tools=2.84.4=h3823947_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - icu=75.1=he0c23c2_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libclang=21.1.0=default_h7df9e1c_0
  - libclang13=21.1.0=default_hadf22e1_0
  - libdeflate=1.25=h51727cc_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.84.4=hfaec014_0
  - libgomp=15.2.0=h8ee18e1_16
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblzma=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.53=h7351971_0
  - libpq=18.1=h7c87ebf_2
  - libsqlite=3.51.1=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.9.4=h2bbff1b_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - packaging=24.1=py38haa95532_0
  - pcre2=10.46=h3402e2f_0
  - pillow=10.4.0=py38h8d10685_0
  - ply=3.11=py38_0
  - pthread-stubs=0.4=h0e40799_1002
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pytesseract=0.3.13=pyhd8ed1ab_0
  - python=3.8.20=h8205438_0
  - python_abi=3.8=2_cp38
  - qt-main=5.15.15=hb098fff_5
  - setuptools=75.1.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.13=h2c6b04d_3
  - tomli=2.0.1=py38haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=h534d264_6
  - pip:
      - async-timeout==4.0.3
      - bleak==0.22.3
      - bleak-winrt==1.2.0
      - cffi==1.17.1
      - future==0.16.0
      - kociemba==1.2.1
      - mouseinfo==0.1.3
      - numpy==1.24.4
      - opencv-contrib-python==4.10.0.84
      - pip==25.0.1
      - pyautogui==0.9.54
      - pycparser==2.22
      - pygetwindow==0.0.9
      - pymsgbox==1.0.9
      - pyperclip==1.9.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - pytweening==1.2.0
      - pyzbar==0.1.9
      - rubik-solver==0.2.0
      - typing-extensions==4.12.2
prefix: D:\Python\envs\common_env
